Repository microsoft/saaslab, pull requests merged in 2021-02, with the labels that each got.

#7 Add app storage options
  app_storage/README.md
  app_storage/app_storage_options.png
Labels: ready to merge

#8 Agenda
  AGENDA.md
Labels: needs review

#13 Update agenda with new structure
  README.md
Labels: needs review

#25 add webinar02 content - Fixes #23
  README.md
Labels: documentation, help wanted, waiting on change

#26 add IaC session
  README.md
Labels: needs review

#32 Reorder marketplace and integration sessions - Fixes #31
  README.md
Labels: needs review

#34 Cleaned up Agenda and added missing info
  README.md
Labels: needs review
